include: package:flutter_lints/flutter.yaml

linter:
  rules:
    #
    no_leading_underscores_for_local_identifiers: false
    package_names: false
    # disable in favor of a single positional boolean parameter
    avoid_positional_boolean_parameters: false
    use_setters_to_change_properties: false
    #
    always_declare_return_types: true
    always_put_required_named_parameters_first: true
    avoid_dynamic_calls: true
    avoid_field_initializers_in_const_classes: true
    avoid_final_parameters: true
    avoid_implementing_value_types: true
    avoid_multiple_declarations_per_line: true
    avoid_type_to_string: true
    avoid_types_on_closure_parameters: true
    avoid_unused_constructor_parameters: true
    cancel_subscriptions: true
    close_sinks: true
    conditional_uri_does_not_exist: true
    directives_ordering: true
    library_names: true
    literal_only_boolean_expressions: true
    no_runtimeType_toString: true
    no_self_assignments: true
    noop_primitive_operations: true
    omit_local_variable_types: true
    omit_obvious_property_types: true
    only_throw_errors: true
    parameter_assignments: true
    prefer_asserts_in_initializer_lists: true
    prefer_const_constructors: true
    prefer_const_declarations: true
    prefer_const_literals_to_create_immutables: true
    prefer_constructors_over_static_methods: true
    prefer_final_in_for_each: true
    prefer_final_locals: true
    prefer_if_elements_to_conditional_expressions: true
    prefer_mixin: true
    prefer_null_aware_method_calls: true
    prefer_relative_imports: true
    prefer_single_quotes: true
    prefer_void_to_null: true
    sized_box_shrink_expand: true
    sort_constructors_first: true
    sort_unnamed_constructors_first: true
    test_types_in_equals: true
    tighten_type_of_initializing_formals: true
    type_annotate_public_apis: true
    unawaited_futures: true
    unnecessary_breaks: true
    unnecessary_lambdas: true
    unnecessary_parenthesis: true
    unnecessary_raw_strings: true
    unnecessary_statements: true
    unreachable_from_main: true
    use_colored_box: true
    use_decorated_box: true
    use_enums: true
    use_is_even_rather_than_modulo: true
    use_late_for_private_fields_and_variables: true
    use_named_constants: true
    use_null_aware_elements: true
    use_raw_strings: true
    use_string_buffers: true
    use_super_parameters: true
    use_test_throws_matchers: true
    use_to_and_as_if_applicable: true
    use_truncating_division: true

analyzer:
  errors:
    invalid_use_of_protected_member: error
  exclude:
    - lib/**.g.dart

formatter:
  page_width: 100
  trailing_commas: preserve